version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"


  bot:
    restart: always
    build: .
    env_file:
      - ./app/.env
    depends_on:
      - db
