version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"

  bot:
    build: .
    env_file:
      - ./app/.env
    depends_on:
      - db
