version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  bot:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
